
package matii_derivada.calculadora;

import java.awt.Color;
import matii_derivada.calculadora.frmCalculadora;

public class frmPagPrincipal extends javax.swing.JFrame {

    int xMouse, yMouse;
    public frmPagPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LogoUCV = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        DerivadaLogo = new javax.swing.JLabel();
        Label_Integrantes = new javax.swing.JLabel();
        Fabio = new javax.swing.JLabel();
        Miguel = new javax.swing.JLabel();
        Nayeli = new javax.swing.JLabel();
        Juan = new javax.swing.JLabel();
        Elmer = new javax.swing.JLabel();
        Fabian = new javax.swing.JLabel();
        FondoIngresar = new javax.swing.JPanel();
        Ingesar = new javax.swing.JLabel();
        scroll = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        BackGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoUCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogotipoUCV_VersiónLarga_Mediana.png"))); // NOI18N
        jPanel2.add(LogoUCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        Titulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("CALCULADORA DE DERIVADAS");
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TituloMouseExited(evt);
            }
        });
        jPanel2.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 90, 760, -1));

        DerivadaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/800px-Tangent_to_a_curve.svg.png"))); // NOI18N
        jPanel2.add(DerivadaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        Label_Integrantes.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Label_Integrantes.setText("INTEGRANTES - GRUPO 4");
        Label_Integrantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_IntegrantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_IntegrantesMouseExited(evt);
            }
        });
        jPanel2.add(Label_Integrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        Fabio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Fabio.setText("FABIO ALEXANDER FELIX TARAZONA");
        Fabio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FabioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FabioMouseExited(evt);
            }
        });
        jPanel2.add(Fabio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        Miguel.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Miguel.setText("MIGUEL ANGEL WILLIAMS LEZAMA GUERRERO ");
        Miguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MiguelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MiguelMouseExited(evt);
            }
        });
        jPanel2.add(Miguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        Nayeli.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Nayeli.setText("NAYELI NOEMI MARTINEZ COCHACHI ");
        Nayeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NayeliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NayeliMouseExited(evt);
            }
        });
        jPanel2.add(Nayeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        Juan.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Juan.setText("JUAN MANUEL PORTOCARRERO RIVA ");
        Juan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JuanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JuanMouseExited(evt);
            }
        });
        jPanel2.add(Juan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        Elmer.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Elmer.setText("ELMER MENDOZA CARHUANCHO ");
        Elmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ElmerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ElmerMouseExited(evt);
            }
        });
        jPanel2.add(Elmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        Fabian.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Fabian.setText("FABIAN ZACARIAS YATACO PULIDO");
        Fabian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FabianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FabianMouseExited(evt);
            }
        });
        jPanel2.add(Fabian, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

        FondoIngresar.setBackground(new java.awt.Color(35, 66, 149));

        Ingesar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Ingesar.setForeground(new java.awt.Color(255, 255, 255));
        Ingesar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ingesar.setText("INGRESAR");
        Ingesar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ingesar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngesarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngesarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngesarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FondoIngresarLayout = new javax.swing.GroupLayout(FondoIngresar);
        FondoIngresar.setLayout(FondoIngresarLayout);
        FondoIngresarLayout.setHorizontalGroup(
            FondoIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ingesar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        FondoIngresarLayout.setVerticalGroup(
            FondoIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ingesar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(FondoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 140, 50));

        scroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scroll.setOpaque(false);
        scroll.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                scrollMouseDragged(evt);
            }
        });
        scroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scrollMousePressed(evt);
            }
        });

        jPanel6.setOpaque(false);
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout scrollLayout = new javax.swing.GroupLayout(scroll);
        scroll.setLayout(scrollLayout);
        scrollLayout.setHorizontalGroup(
            scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scrollLayout.createSequentialGroup()
                .addGap(0, 743, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        scrollLayout.setVerticalGroup(
            scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scrollLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 800, 30));

        BackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 760, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scrollMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_scrollMousePressed

    private void scrollMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_scrollMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        
    }//GEN-LAST:event_jPanel6MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setBackground(new Color(0, 255, 0));
        jLabel1.setForeground(Color.red);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
       jLabel1.setBackground(Color.white);
       jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel1MouseExited

    private void IngesarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngesarMouseEntered
       Ingesar.setForeground(Color.white);
       FondoIngresar.setBackground(new Color(116, 200, 255));
       //FondoIngresar.setBackground(new Color(36, 92, 148));
    }//GEN-LAST:event_IngesarMouseEntered

    private void IngesarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngesarMouseExited
        Ingesar.setForeground(Color.white);
        FondoIngresar.setBackground(new Color(35,66,149));
    }//GEN-LAST:event_IngesarMouseExited

    private void IngesarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngesarMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculadora().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_IngesarMouseClicked

    private void FabioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FabioMouseEntered
        Fabio.setForeground(Color.red);
    }//GEN-LAST:event_FabioMouseEntered

    private void FabioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FabioMouseExited
        Fabio.setForeground(Color.black);
    }//GEN-LAST:event_FabioMouseExited

    private void NayeliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NayeliMouseEntered
        Nayeli.setForeground(Color.red);
    }//GEN-LAST:event_NayeliMouseEntered

    private void NayeliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NayeliMouseExited
        Nayeli.setForeground(Color.black);
    }//GEN-LAST:event_NayeliMouseExited

    private void JuanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuanMouseEntered
        Juan.setForeground(Color.red);
    }//GEN-LAST:event_JuanMouseEntered

    private void JuanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuanMouseExited
        Juan.setForeground(Color.black);
    }//GEN-LAST:event_JuanMouseExited

    private void FabianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FabianMouseEntered
        Fabian.setForeground(Color.red);
    }//GEN-LAST:event_FabianMouseEntered

    private void FabianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FabianMouseExited
        Fabian.setForeground(Color.black);
    }//GEN-LAST:event_FabianMouseExited

    private void MiguelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiguelMouseEntered
        Miguel.setForeground(new Color(35,66,149));
    }//GEN-LAST:event_MiguelMouseEntered

    private void MiguelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiguelMouseExited
        Miguel.setForeground(Color.black);
    }//GEN-LAST:event_MiguelMouseExited

    private void ElmerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElmerMouseEntered
        Elmer.setForeground(new Color(35,66,149));
    }//GEN-LAST:event_ElmerMouseEntered

    private void ElmerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElmerMouseExited
        Elmer.setForeground(Color.black);
    }//GEN-LAST:event_ElmerMouseExited

    private void Label_IntegrantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_IntegrantesMouseEntered
        Label_Integrantes.setForeground(new Color(116, 200, 255));
    }//GEN-LAST:event_Label_IntegrantesMouseEntered

    private void Label_IntegrantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_IntegrantesMouseExited
        Label_Integrantes.setForeground(Color.black);
    }//GEN-LAST:event_Label_IntegrantesMouseExited

    private void TituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseEntered
        Titulo.setForeground(Color.red);
    }//GEN-LAST:event_TituloMouseEntered

    private void TituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseExited
       Titulo.setForeground(Color.black);
    }//GEN-LAST:event_TituloMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPagPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel DerivadaLogo;
    private javax.swing.JLabel Elmer;
    private javax.swing.JLabel Fabian;
    private javax.swing.JLabel Fabio;
    private javax.swing.JPanel FondoIngresar;
    private javax.swing.JLabel Ingesar;
    private javax.swing.JLabel Juan;
    private javax.swing.JLabel Label_Integrantes;
    private javax.swing.JLabel LogoUCV;
    private javax.swing.JLabel Miguel;
    private javax.swing.JLabel Nayeli;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel scroll;
    // End of variables declaration//GEN-END:variables
}
