/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package matii_derivada.calculadora.pages;

import java.awt.Color;

/**
 *
 * @author juanp
 */
public class Bienvenida extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenidad
     */
    public Bienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Doc = new javax.swing.JLabel();
        Efrain = new javax.swing.JLabel();
        MatematicaII = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Doc.setBackground(new java.awt.Color(255, 255, 255));
        Doc.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Doc.setForeground(new java.awt.Color(255, 255, 255));
        Doc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Doc.setText("Doc:");
        Doc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DocMouseExited(evt);
            }
        });
        jPanel1.add(Doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 30));

        Efrain.setBackground(new java.awt.Color(255, 255, 255));
        Efrain.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        Efrain.setForeground(new java.awt.Color(255, 255, 255));
        Efrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Efrain.setText("EFRAIN ISIDRO CERAFIN URBANO");
        Efrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EfrainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EfrainMouseExited(evt);
            }
        });
        jPanel1.add(Efrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 50));

        MatematicaII.setBackground(new java.awt.Color(255, 255, 255));
        MatematicaII.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        MatematicaII.setForeground(new java.awt.Color(255, 255, 255));
        MatematicaII.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MatematicaII.setText("MATEMÁTICA II");
        MatematicaII.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MatematicaIIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MatematicaIIMouseExited(evt);
            }
        });
        jPanel1.add(MatematicaII, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/photo1669819432 (1).jpeg"))); // NOI18N
        Background.setText("B");
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void EfrainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EfrainMouseEntered
        Efrain.setForeground(Color.red);
    }//GEN-LAST:event_EfrainMouseEntered

    private void EfrainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EfrainMouseExited
        Efrain.setForeground(Color.white);
    }//GEN-LAST:event_EfrainMouseExited

    private void DocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DocMouseEntered
        Doc.setForeground(Color.red);
    }//GEN-LAST:event_DocMouseEntered

    private void DocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DocMouseExited
        Doc.setForeground(Color.white);
    }//GEN-LAST:event_DocMouseExited

    private void MatematicaIIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatematicaIIMouseEntered
        MatematicaII.setForeground(Color.red);
    }//GEN-LAST:event_MatematicaIIMouseEntered

    private void MatematicaIIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatematicaIIMouseExited
        MatematicaII.setForeground(Color.WHITE);
    }//GEN-LAST:event_MatematicaIIMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Doc;
    private javax.swing.JLabel Efrain;
    private javax.swing.JLabel MatematicaII;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
