
package matii_derivada.calculadora.pages;

import java.awt.Color;
import org.math.plot.Plot2DPanel;

public class Page2 extends javax.swing.JPanel {

    
    public Page2() {
        initComponents();
        grafica.setBounds(300, 10, 390, 300);
        add(grafica);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        x0 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        background_graficar = new javax.swing.JPanel();
        btonGraficar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        raiz = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        Content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 10, 330));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        Content.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, 190));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        Content.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 10, 110));

        jPanel3.setBackground(new java.awt.Color(3, 46, 90));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRAFICAR FUNCIÓN");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 760, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogotipoUCV_VersiónLarga_Mediana.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 60, -1));

        Content.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 760, 60));

        x0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x0ActionPerformed(evt);
            }
        });
        Content.add(x0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, 40));

        jLabel3.setText("DIGITAR FUNCIÓN");
        Content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setText("X1");
        Content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        Content.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 40));

        jLabel5.setText("PARAMETROS ");
        Content.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel6.setText("X2");
        Content.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1ActionPerformed(evt);
            }
        });
        Content.add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 60, 40));

        jLabel7.setText("ERROR:");
        Content.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, -1));

        e.setText("1e-6");
        Content.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel9.setText("ENTERO:");
        Content.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, -1));

        n.setText("100");
        Content.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        background_graficar.setBackground(new java.awt.Color(255, 51, 51));
        background_graficar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btonGraficar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btonGraficar.setForeground(new java.awt.Color(255, 255, 255));
        btonGraficar.setText("GRAFICAR");
        btonGraficar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btonGraficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btonGraficarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btonGraficarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btonGraficarMouseExited(evt);
            }
        });
        background_graficar.add(btonGraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Content.add(background_graficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 140, 40));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel11.setText("RAÍZ");
        Content.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });
        Content.add(raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 130, 40));
        Content.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 340, 210));

        add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void x0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x0ActionPerformed

    private void x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1ActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raizActionPerformed

    private void btonGraficarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btonGraficarMouseEntered
        background_graficar.setBackground(Color.white);
        btonGraficar.setForeground(Color.red);
    }//GEN-LAST:event_btonGraficarMouseEntered

    private void btonGraficarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btonGraficarMouseExited
        background_graficar.setBackground(Color.red);
        btonGraficar.setForeground(Color.white);
    }//GEN-LAST:event_btonGraficarMouseExited

    private void btonGraficarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btonGraficarMouseClicked
        String def = f.getText();
        double x0_1 = Double.parseDouble(x0.getText());
        double x1_1 = Double.parseDouble(x1.getText());
        double le = Double.parseDouble(e.getText());
        double ln = Integer.parseInt(n.getText());
        x0_1 = 0;
        x1_1 = 0;
        funcion ff = new funcion(def);
        metodo s = new metodo();
        double r = s.raiz(ff, x0_1, x1_1, ln, le);
        raiz.setText(""+r);
        
        double[] x = new double[200];
        double[] y = new double[200];
        double xi = x0_1 - x1_1 - 10; 
        for (int i = 0; i < 200; i++){
            x[i] = xi+1*0.1;
            y[i] = ff.evaluar(x[i]);
        }
        
    }//GEN-LAST:event_btonGraficarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel background_graficar;
    private javax.swing.JLabel btonGraficar;
    private javax.swing.JLabel e;
    private javax.swing.JTextField f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel n;
    private javax.swing.JTextField raiz;
    private javax.swing.JTextField x0;
    private javax.swing.JTextField x1;
    // End of variables declaration//GEN-END:variables
    Plot2DPanel grafica = new Plot2DPanel();
}