/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package matii_derivada.calculadora.pages;

import java.awt.Color;

/**
 *
 * @author juanp
 */
public class Bienvenida extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenidad
     */
    public Bienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texto3 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        texto0 = new javax.swing.JLabel();
        Doc = new javax.swing.JLabel();
        Efrain = new javax.swing.JLabel();
        MatematicaII = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto3.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        texto3.setForeground(new java.awt.Color(255, 204, 0));
        texto3.setText("en el curso de MATEMÁTICA II.");
        texto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto3MouseExited(evt);
            }
        });
        jPanel1.add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 20));

        texto2.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 204, 0));
        texto2.setText("aplicativo hecho en Java por el grupo 4 como prouecto");
        texto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto2MouseExited(evt);
            }
        });
        jPanel1.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 20));

        texto1.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 204, 0));
        texto1.setText("Presentamos la calculadora de derivadas v0.04");
        texto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto1MouseExited(evt);
            }
        });
        jPanel1.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        texto0.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        texto0.setForeground(new java.awt.Color(255, 204, 0));
        texto0.setText("¡Bienvenidos!");
        texto0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto0MouseExited(evt);
            }
        });
        jPanel1.add(texto0, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        Doc.setBackground(new java.awt.Color(255, 255, 255));
        Doc.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Doc.setForeground(new java.awt.Color(255, 255, 255));
        Doc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Doc.setText("Prof.");
        Doc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DocMouseExited(evt);
            }
        });
        jPanel1.add(Doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 30));

        Efrain.setBackground(new java.awt.Color(255, 255, 255));
        Efrain.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        Efrain.setForeground(new java.awt.Color(255, 255, 255));
        Efrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Efrain.setText("EFRAIN ISIDRO CERAFIN URBANO");
        Efrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EfrainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EfrainMouseExited(evt);
            }
        });
        jPanel1.add(Efrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 50));

        MatematicaII.setBackground(new java.awt.Color(255, 255, 255));
        MatematicaII.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        MatematicaII.setForeground(new java.awt.Color(255, 255, 255));
        MatematicaII.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MatematicaII.setText("MATEMÁTICA II");
        MatematicaII.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MatematicaIIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MatematicaIIMouseExited(evt);
            }
        });
        jPanel1.add(MatematicaII, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/photo1669819432 (1).jpeg"))); // NOI18N
        Background.setText("B");
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void EfrainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EfrainMouseEntered
        Efrain.setForeground(Color.red);
    }//GEN-LAST:event_EfrainMouseEntered

    private void EfrainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EfrainMouseExited
        Efrain.setForeground(Color.white);
    }//GEN-LAST:event_EfrainMouseExited

    private void DocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DocMouseEntered
        Doc.setForeground(Color.red);
    }//GEN-LAST:event_DocMouseEntered

    private void DocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DocMouseExited
        Doc.setForeground(Color.white);
    }//GEN-LAST:event_DocMouseExited

    private void MatematicaIIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatematicaIIMouseEntered
        MatematicaII.setForeground(Color.red);
    }//GEN-LAST:event_MatematicaIIMouseEntered

    private void MatematicaIIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatematicaIIMouseExited
        MatematicaII.setForeground(Color.WHITE);
    }//GEN-LAST:event_MatematicaIIMouseExited

    private void texto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto1MouseEntered
        texto1.setForeground(Color.white);
    }//GEN-LAST:event_texto1MouseEntered

    private void texto1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto1MouseExited
        texto1.setForeground(new Color(255,204,0));
    }//GEN-LAST:event_texto1MouseExited

    private void texto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_texto2MouseClicked

    private void texto2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto2MouseEntered
        texto2.setForeground(Color.white);
    }//GEN-LAST:event_texto2MouseEntered

    private void texto2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto2MouseExited
        texto2.setForeground(new Color(255,204,0));
    }//GEN-LAST:event_texto2MouseExited

    private void texto3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto3MouseEntered
        texto3.setForeground(Color.white);
    }//GEN-LAST:event_texto3MouseEntered

    private void texto3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto3MouseExited
        texto3.setForeground(new Color(255,204,0));
    }//GEN-LAST:event_texto3MouseExited

    private void texto0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto0MouseEntered
        texto0.setForeground(Color.red);
    }//GEN-LAST:event_texto0MouseEntered

    private void texto0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto0MouseExited
        texto0.setForeground(new Color(255,204,0));
    }//GEN-LAST:event_texto0MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Doc;
    private javax.swing.JLabel Efrain;
    private javax.swing.JLabel MatematicaII;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel texto0;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    // End of variables declaration//GEN-END:variables
}
