/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package matii_derivada.calculadora.pages;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public class Page1 extends javax.swing.JPanel {

    /**
     * Creates new form Page1
     */
    public Page1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jEntero1 = new javax.swing.JTextField();
        jComboSigno2 = new javax.swing.JComboBox<>();
        jEntero2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jExponente1 = new javax.swing.JTextField();
        jResult1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jExponente3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jEntero3 = new javax.swing.JTextField();
        jbOperar = new javax.swing.JButton();
        jL_Line1_Enetero1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jL_Line1_Exponente1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLSigno_Line1 = new javax.swing.JLabel();
        jL_Line1_Enetero2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jL_Line1_Exponente2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jL_Line1_Exponente3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jL_Line1_Enetero3 = new javax.swing.JTextField();
        jLSigno_Line2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jL_Line2_resultado2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jL_Line1_resultado = new javax.swing.JTextField();
        jL_Line2_result_entero = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jL_Line2_result_exponente = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jL_Line2_resultado = new javax.swing.JTextField();
        jL_Line2_resultado1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jExponente2 = new javax.swing.JTextField();
        jComboSigno1 = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        Content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 10, 330));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        Content.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, 190));

        jPanel3.setBackground(new java.awt.Color(3, 46, 90));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DERIVADA IMPLÍCITA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 760, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogotipoUCV_VersiónLarga_Mediana.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 60, -1));

        Content.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 760, 60));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        Content.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 10, 110));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel3.setText("Y");
        Content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 30, 40));

        jEntero1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jEntero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jEntero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntero1ActionPerformed(evt);
            }
        });
        Content.add(jEntero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, 30));

        jComboSigno2.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jComboSigno2.setForeground(new java.awt.Color(255, 51, 51));
        jComboSigno2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        jComboSigno2.setBorder(null);
        jComboSigno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSigno2ActionPerformed(evt);
            }
        });
        Content.add(jComboSigno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 90, 30));

        jEntero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jEntero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntero2ActionPerformed(evt);
            }
        });
        Content.add(jEntero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 40, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel4.setText("=");
        Content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 30, 40));

        jExponente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExponente1ActionPerformed(evt);
            }
        });
        Content.add(jExponente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 40, 40));

        jResult1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jResult1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jResult1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jResult1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jResult1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResult1ActionPerformed(evt);
            }
        });
        Content.add(jResult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 80, 40));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel5.setText("Y");
        Content.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 30, 40));

        jExponente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExponente3ActionPerformed(evt);
            }
        });
        Content.add(jExponente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 40, 40));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel6.setText("Y");
        Content.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 30, 40));

        jEntero3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jEntero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntero3ActionPerformed(evt);
            }
        });
        Content.add(jEntero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 40, 30));

        jbOperar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        jbOperar.setBorder(null);
        jbOperar.setBorderPainted(false);
        jbOperar.setContentAreaFilled(false);
        jbOperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOperarActionPerformed(evt);
            }
        });
        Content.add(jbOperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 50, 50));

        jL_Line1_Enetero1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jL_Line1_Enetero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jL_Line1_Enetero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_Line1_Enetero1ActionPerformed(evt);
            }
        });
        Content.add(jL_Line1_Enetero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 30));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel7.setText("Y");
        Content.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 30, 40));

        jL_Line1_Exponente1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jL_Line1_Exponente1.setText("X");
        Content.add(jL_Line1_Exponente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("dx");
        Content.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 40, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("----");
        Content.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 60, 20));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("dy");
        Content.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 40, 30));

        jLSigno_Line1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLSigno_Line1.setForeground(new java.awt.Color(255, 51, 51));
        jLSigno_Line1.setText("+");
        Content.add(jLSigno_Line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 30, -1));

        jL_Line1_Enetero2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jL_Line1_Enetero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jL_Line1_Enetero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_Line1_Enetero2ActionPerformed(evt);
            }
        });
        Content.add(jL_Line1_Enetero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 40, 30));

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel13.setText("Y");
        Content.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, 40));

        jL_Line1_Exponente2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jL_Line1_Exponente2.setText("X");
        Content.add(jL_Line1_Exponente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("dy");
        Content.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 40, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setText("----");
        Content.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 60, 20));

        jLabel17.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("dx");
        Content.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 40, 30));

        jLabel18.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("dy");
        Content.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 40, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel19.setText("----");
        Content.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 60, 20));

        jLabel20.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("dx");
        Content.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 40, 30));

        jL_Line1_Exponente3.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jL_Line1_Exponente3.setText("X");
        Content.add(jL_Line1_Exponente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel22.setText("X");
        Content.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 30, 40));

        jL_Line1_Enetero3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jL_Line1_Enetero3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jL_Line1_Enetero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_Line1_Enetero3ActionPerformed(evt);
            }
        });
        Content.add(jL_Line1_Enetero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 40, 30));

        jLSigno_Line2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLSigno_Line2.setForeground(new java.awt.Color(255, 51, 51));
        jLSigno_Line2.setText("+");
        Content.add(jLSigno_Line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 30, -1));

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel24.setText("=");
        Content.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 30, 40));

        jL_Line2_resultado2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jL_Line2_resultado2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jL_Line2_resultado2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jL_Line2_resultado2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jL_Line2_resultado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_Line2_resultado2ActionPerformed(evt);
            }
        });
        Content.add(jL_Line2_resultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 140, 40));

        jLabel25.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("dy");
        Content.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel26.setText("----");
        Content.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, 20));

        jLabel27.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("dx");
        Content.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 40, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("=");
        Content.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jL_Line1_resultado.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jL_Line1_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jL_Line1_resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jL_Line1_resultado.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jL_Line1_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_Line1_resultadoActionPerformed(evt);
            }
        });
        Content.add(jL_Line1_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 80, 40));

        jL_Line2_result_entero.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jL_Line2_result_entero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Line2_result_entero.setText("0");
        Content.add(jL_Line2_result_entero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 50, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("(");
        Content.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel31.setFont(new java.awt.Font("Roboto Medium", 0, 45)); // NOI18N
        jLabel31.setText("x");
        Content.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 30, 40));

        jL_Line2_result_exponente.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jL_Line2_result_exponente.setText("X");
        Content.add(jL_Line2_result_exponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jLabel33.setFont(new java.awt.Font("Roboto Light", 1, 36)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("dy");
        Content.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 50, 40));

        jLabel34.setFont(new java.awt.Font("Roboto Light", 1, 36)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("dx");
        Content.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 40, 30));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Content.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 60, 20));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText(")=");
        Content.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel38.setText("--------");
        Content.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 160, 20));

        jL_Line2_resultado.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jL_Line2_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jL_Line2_resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jL_Line2_resultado.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jL_Line2_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_Line2_resultadoActionPerformed(evt);
            }
        });
        Content.add(jL_Line2_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 140, 40));

        jL_Line2_resultado1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jL_Line2_resultado1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jL_Line2_resultado1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jL_Line2_resultado1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jL_Line2_resultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_Line2_resultado1ActionPerformed(evt);
            }
        });
        Content.add(jL_Line2_resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 140, 40));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel37.setText("----------------------------------------------");
        Content.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 630, 20));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel39.setText("----------------------------------------------");
        Content.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 630, 20));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dos-lineas.png"))); // NOI18N
        Content.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 60, 80));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel41.setText("----");
        Content.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 60, 20));

        jExponente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExponente2ActionPerformed(evt);
            }
        });
        Content.add(jExponente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 40, 40));

        jComboSigno1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jComboSigno1.setForeground(new java.awt.Color(255, 51, 51));
        jComboSigno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        jComboSigno1.setBorder(null);
        jComboSigno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSigno1ActionPerformed(evt);
            }
        });
        Content.add(jComboSigno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 30));

        add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void jEntero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEntero1ActionPerformed

    private void jComboSigno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSigno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSigno2ActionPerformed

    private void jEntero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEntero2ActionPerformed

    private void jExponente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExponente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jExponente1ActionPerformed

    private void jResult1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResult1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResult1ActionPerformed

    private void jExponente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExponente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jExponente3ActionPerformed

    private void jEntero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEntero3ActionPerformed

    private void jL_Line1_Enetero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_Line1_Enetero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Line1_Enetero1ActionPerformed

    private void jL_Line1_Enetero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_Line1_Enetero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Line1_Enetero2ActionPerformed

    private void jL_Line1_Enetero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_Line1_Enetero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Line1_Enetero3ActionPerformed

    private void jL_Line2_resultado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_Line2_resultado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Line2_resultado2ActionPerformed

    private void jL_Line1_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_Line1_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Line1_resultadoActionPerformed

    private void jL_Line2_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_Line2_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Line2_resultadoActionPerformed

    private void jL_Line2_resultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_Line2_resultado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Line2_resultado1ActionPerformed

    private void jExponente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExponente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jExponente2ActionPerformed

    private void jbOperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOperarActionPerformed
        String campo;
        
        campo = VerificaCampos();
        if(campo.equals(""))
        {
            // Extramemos todos los numeros de la funcion
            int entero1 = Integer.parseInt(jEntero1.getText());
            int entero2 = Integer.parseInt(jEntero2.getText());
            int entero3 = Integer.parseInt(jEntero3.getText());
            int exponente1 = Integer.parseInt(jExponente1.getText());
            int exponente2 = Integer.parseInt(jExponente2.getText());
            int exponente3 = Integer.parseInt(jExponente3.getText());
            String signo1 = jComboSigno1.getSelectedItem().toString();
            String signo2 = jComboSigno2.getSelectedItem().toString();
            int Resultado1 = Integer.parseInt(jResult1.getText());

            entero1 = entero1*exponente1;
            exponente1 = exponente1-1;
            entero2 = entero2*exponente2;
            exponente2 = exponente2-1;
            entero3 = entero3*exponente3;
            exponente3 = exponente3-1;

            jLSigno_Line1.setText(signo1);
            jLSigno_Line2.setText(signo2);
            jL_Line1_Exponente1.setText(Integer.toString(exponente1));
            jL_Line1_Exponente2.setText(Integer.toString(exponente2));
            jL_Line1_Exponente3.setText(Integer.toString(exponente3));
            jL_Line1_Enetero1.setText(Integer.toString(entero1));
            jL_Line1_Enetero2.setText(Integer.toString(entero2));
            jL_Line1_Enetero3.setText(Integer.toString(entero3));
            jL_Line1_resultado.setText("0");
            jL_Line2_resultado.setText(""+entero1+"Y"+"^"+exponente1+signo1+entero2+"Y"+"^"+exponente2);
            jL_Line2_result_entero.setText(Integer.toString(entero3));
            jL_Line2_result_exponente.setText(Integer.toString(exponente3));
            jL_Line2_resultado1.setText(""+entero3+"X"+"^"+exponente3);
            jL_Line2_resultado2.setText(""+entero1+"Y"+"^"+exponente1+signo1+entero2+"Y"+"^"+exponente2);
        }
        else JOptionPane.showMessageDialog(null, "Verifique los datos en el campo de "+campo);
        
        
        
    }//GEN-LAST:event_jbOperarActionPerformed

    String VerificaCampos() 
    {
        if(jEntero1.getText().equals("")){
            jEntero1.setBackground(Color.RED);
            return "PRIMER ENTERO";
            }
        else if(jEntero2.getText().equals("")){
            jEntero1.setBackground(Color.WHITE);
            jEntero2.setBackground(Color.RED);
            return "Segundo Entero";
            }
        else if(jEntero3.getText().equals("")){
            jEntero2.setBackground(Color.WHITE);
            jEntero3.setBackground(Color.RED);
            return "Tercer Entero";
            }
        else if(jExponente1.getText().equals("")){
            jEntero3.setBackground(Color.WHITE);
            jExponente1.setBackground(Color.RED);
            return "Primer exponente";
            }
        else if(jExponente2.getText().equals("")){
            jExponente1.setBackground(Color.WHITE);
            jExponente2.setBackground(Color.RED);
            return "Segundo exponente";
            }
        else if(jExponente3.getText().equals("")){
            jExponente2.setBackground(Color.WHITE);
            jExponente3.setBackground(Color.RED);
            return "Tercer exponente";
            }
        else if(jResult1.getText().equals("")){
            jExponente3.setBackground(Color.WHITE);
            jResult1.setBackground(Color.RED);
            return "Resultado de la derivada";
            }
        //Si todos los jText estan con datos, retornamos un texto vacio.
        else{
            jEntero1.setBackground(Color.WHITE);
            jEntero2.setBackground(Color.WHITE);
            jEntero3.setBackground(Color.WHITE);
            jExponente1.setBackground(Color.WHITE);
            jExponente2.setBackground(Color.WHITE);
            jExponente3.setBackground(Color.WHITE);
            jResult1.setBackground(Color.WHITE);
            return "";}
    }
    
    private void jComboSigno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSigno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSigno1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JComboBox<String> jComboSigno1;
    private javax.swing.JComboBox<String> jComboSigno2;
    private javax.swing.JTextField jEntero1;
    private javax.swing.JTextField jEntero2;
    private javax.swing.JTextField jEntero3;
    private javax.swing.JTextField jExponente1;
    private javax.swing.JTextField jExponente2;
    private javax.swing.JTextField jExponente3;
    private javax.swing.JLabel jLSigno_Line1;
    private javax.swing.JLabel jLSigno_Line2;
    private javax.swing.JTextField jL_Line1_Enetero1;
    private javax.swing.JTextField jL_Line1_Enetero2;
    private javax.swing.JTextField jL_Line1_Enetero3;
    private javax.swing.JLabel jL_Line1_Exponente1;
    private javax.swing.JLabel jL_Line1_Exponente2;
    private javax.swing.JLabel jL_Line1_Exponente3;
    private javax.swing.JTextField jL_Line1_resultado;
    private javax.swing.JLabel jL_Line2_result_entero;
    private javax.swing.JLabel jL_Line2_result_exponente;
    private javax.swing.JTextField jL_Line2_resultado;
    private javax.swing.JTextField jL_Line2_resultado1;
    private javax.swing.JTextField jL_Line2_resultado2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jResult1;
    private javax.swing.JButton jbOperar;
    // End of variables declaration//GEN-END:variables
}
